before_script:
  - git checkout -b master
  - apt-get -yqq update
  - apt-get -yqq install build-essential libtool gcc-4.8 g++-4.8 make cmake openssl clang-3.5 mysql-server mysql-client
  - apt-get -yqq install libssl-dev libmysqlclient-dev libmysql++-dev libreadline6-dev zlib1g-dev libbz2-dev libzmq3-dev
  - apt-get -yqq install libboost1.55-dev libboost-thread1.55-dev libboost-filesystem1.55-dev libboost-system1.55-dev libboost-program-options1.55-dev libboost-iostreams1.55-dev
  - export CC=clang CXX=clang++
  - /etc/init.d/mysqld start

install:
  script:
    - mysql -uroot -e 'create database test_mysql;'
    - mkdir bin
    - cd bin
    - cmake ../ -DWITH_WARNINGS=1 -DWITH_COREDEBUG=0 -DUSE_COREPCH=1 -DUSE_SCRIPTPCH=1 -DTOOLS=1 -DSCRIPTS=1 -DSERVERS=1 -DNOJEM=1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS="-Werror" -DCMAKE_CXX_FLAGS="-Werror"
    - cd ..
    - chmod +x contrib/check_updates.sh
    - $CXX --version
    - mysql -uroot < sql/create/create_mysql.sql
    - mysql -utrinity -ptrinity auth < sql/base/auth_database.sql
    - ./contrib/check_updates.sh auth auth
    - mysql -utrinity -ptrinity characters < sql/base/characters_database.sql
    - ./contrib/check_updates.sh characters characters
    - mysql -utrinity -ptrinity world < sql/base/dev/world_database.sql
    - cat sql/updates/world/*.sql | mysql -utrinity -ptrinity world
    - mysql -uroot < sql/create/drop_mysql.sql
    - cd bin
    - make -j 10 -k
