[package]
name = "libenturion"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "lib.rs"

[dependencies]
enturion_shared = { path = "shared" }
libmpq-rs = { path = "libmpq-rs" }

[workspace]
resolver = "2"
members = [
    "authserver",
    "libmpq-rs",
    "shared",
]
