on:
  issues:
    types: [opened]

jobs:
  tag_issues:
    runs-on: ubuntu-latest
    name: Issue Labeler
    steps:
    - name: Issue Labeler
      id: issue-labeler
      uses: TrinityCore/GitHub-Actions@issue-labeler-prod
      with:
        token: ${{ secrets.GITHUB_TOKEN }}