on:
  pull_request:
    types: [opened]

jobs:
  tag_issues:
    runs-on: ubuntu-latest
    name: Pull Request Labeler
    steps:
    - name: Pull Request Labeler
      id: pr-labeler
      uses: TrinityCore/GitHub-Actions@pr-labeler-prod
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
